import pandas as pd
import numpy as np
import google.generativeai as genai
import os
import sys
from dotenv import load_dotenv

# --- 1. Configurations ---
# Loads environment variables from a .env file located in the same directory or project root
load_dotenv()

API_KEY = os.environ.get("GEMINI_API_KEY")
if not API_KEY:
    print("Error: GEMINI_API_KEY environment variable not set.")
    sys.exit(1)

genai.configure(api_key=API_KEY)
model = genai.GenerativeModel('gemini-3-flash-preview') # Or the newest available model

# Grid Thresholds for Physics Rules
V_MIN_THRESHOLD = 0.95
V_MAX_THRESHOLD = 1.05
LINE_LOADING_WARNING = 80.0
LINE_LOADING_CRITICAL = 95.0

def load_predictions(predictions_csv):
    """Loads the forecasted telemetry predictions CSV."""
    if not os.path.exists(predictions_csv):
        print(f"Error: {predictions_csv} not found.")
        sys.exit(1)
    df = pd.read_csv(predictions_csv)
    return df

def analyze_grid_state(df_hour):
    """
    Analyzes a single hour of forecasted grid data against strict physics rules
    to generate a context block for the LLM.
    """
    issues = []
    
    # Check Voltages
    if df_hour['V_Min_pu'] < V_MIN_THRESHOLD:
        issues.append(f"UNDERVOLTAGE: System minimum voltage dropped to {df_hour['V_Min_pu']:.3f} p.u. (Threshold: {V_MIN_THRESHOLD}).")
    if df_hour['V_Max_pu'] > V_MAX_THRESHOLD:
        issues.append(f"OVERVOLTAGE: System maximum voltage reached {df_hour['V_Max_pu']:.3f} p.u. (Threshold: {V_MAX_THRESHOLD}).")
        
    # Check line loadings
    if df_hour['Max_Line_Loading_pct'] > LINE_LOADING_CRITICAL:
        issues.append(f"CRITICAL BOTTLENECK: Line loading at {df_hour['Max_Line_Loading_pct']:.1f}%. Risk of thermal overload/failure.")
    elif df_hour['Max_Line_Loading_pct'] > LINE_LOADING_WARNING:
        issues.append(f"WARNING: High line loading detected at {df_hour['Max_Line_Loading_pct']:.1f}%.")
        
    return issues

def generate_llm_report(df_forecast):
    """
    Feeds the forecasted anomalies and general grid state into Gemini
    to generate an actionable grid operation report.
    """
    print("Analyzing predictions and generating prompt...")
    
    # We'll aggregate the worst issues over the forecasted period
    total_hours = len(df_forecast)
    critical_hours = []
    
    for _, row in df_forecast.iterrows():
        issues = analyze_grid_state(row)
        if issues:
            timestamp = row.get('Timestamp', f"Hour {row.get('Hour', 'Unknown')}")
            critical_hours.append(f"[{timestamp}] Issues: " + " | ".join(issues))
            
    # Extract overall metrics for context
    avg_load = df_forecast['Total_Load_MW'].mean()
    max_load = df_forecast['Total_Load_MW'].max()
    avg_solar = df_forecast['Solar_MW'].mean()
    avg_wind = df_forecast['Wind_MW'].mean()
    total_loss = df_forecast['Total_Loss_MW'].sum()
    
    prompt = f"""
You are an expert microgrid operator and automated grid controller. 
I am providing you with a forecasted power flow summary generated by a CNN-LSTM model for a modified IEEE 13-Bus system in Kerala over a {total_hours}-hour period.

**Grid Analytics Summary:**
- Average Load: {avg_load:.2f} MW (Peak: {max_load:.2f} MW)
- Average Solar Gen: {avg_solar:.2f} MW
- Average Wind Gen: {avg_wind:.2f} MW
- Cumulative Predicted System Losses: {total_loss:.2f} MW

**Critical Detected Rule Violations:**
"""
    if not critical_hours:
        prompt += "No physics rule violations detected. Grid operates within nominal bounds.\n"
    else:
        prompt += "\n".join(critical_hours) + "\n"

    prompt += """
**Your Task:**
1. Provide a concise executive summary of the forecasted grid stability.
2. If violations (undervoltage, overvoltage, overloading) are listed, identify the likely root causes based on the generation vs load balance.
3. Recommend actionable strategies (e.g., active/reactive power curtailment from DERs, load shedding, islanding feasibility) to mitigate these forecasted issues before they happen in real-time.
"""
    
    print("\nQuerying Gemini API...")
    try:
        response = model.generate_content(prompt)
        print("\n" + "="*60)
        print("🤖 AI MICROGRID ANALYST REPORT")
        print("="*60)
        print(response.text)
        print("="*60)
        
        # Save report
        with open("gemini_prediction_report.md", "w") as f:
            f.write(response.text)
        print("\nReport saved to 'gemini_prediction_report.md'.")
        return response.text
        
    except Exception as e:
        error_msg = f"Failed to generate report from Gemini: {e}"
        print(error_msg)
        return f"**Error**: {error_msg}"

if __name__ == "__main__":
    # Ensure you have a predictions CSV file generated by your test/eval script
    predictions_file = "forecast_predictions.csv" 
    
    if not os.path.exists(predictions_file):
        print(f"Please ensure your ML script saves a '{predictions_file}' before running this summarizer.")
        print("Creating a dummy file for demonstration...")
        # Create a dummy for demonstration if real one doesn't exist
        dummy_data = pd.DataFrame({
            'Hour': [0, 1, 2],
            'Timestamp': ['2023-01-01 12:00:00', '2023-01-01 13:00:00', '2023-01-01 14:00:00'],
            'Total_Load_MW': [3.5, 3.8, 3.9],
            'Solar_MW': [0.8, 0.9, 0.4],
            'Wind_MW': [0.2, 0.1, 0.0],
            'V_Min_pu': [0.96, 0.94, 0.91], # Trigger undervoltage
            'V_Max_pu': [1.01, 1.01, 1.01],
            'Max_Line_Loading_pct': [75.0, 85.0, 98.0], # Trigger overload
            'Total_Loss_MW': [0.05, 0.08, 0.12]
        })
        dummy_data.to_csv(predictions_file, index=False)

    
    df_pred = load_predictions(predictions_file)
    generate_llm_report(df_pred)
